[package]
name = "keylogger"
version = "0.1.0"
edition = "2024"

[dependencies]
argparse = "0.2.2"
evdev = "0.13.2"
libc = "0.2.180"
mio = { version = "1.1.1", features = ["os-poll"] }


[features]
wayland = []
