[package]
name = "tokio-graceful-shutdown"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
tokio = { version = "1.49.0", features = ["full", "rt", "signal"] }
tokio-util = "0.7.18"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
