[package]
name = "os_keyboard_processor"
version = "0.1.0"
edition = "2024"

[dependencies]
conquer-once = { version = "0.4", default-features = false }
crossbeam-queue = { version = "0.3", features = ["alloc"], default-features = false }
x86_64 = "0.15.2"
